spring:
  application:
    name: campaign
  profiles:
    active: dev
  datasource:
    url: ${postgre.url}
    username: ${postgre.username}
    password: ${postgre.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    vault:
      kv:
        enabled: true
        backend: kv
      authentication: TOKEN
      token: ${TOKEN_VAULT}
      scheme: http
      host: 127.0.0.1
      port: 8200
  config:
    import: vault://
  main:
    allow-circular-references: true

server:
  port: 5002

myjwt:
#  mysecret: Pulling this off from vault
  expire: 30


